### ISSUE TITLE
INIファイル書き換えの機能拡張

### ISSUE THREAD

**Issue by turbou** [turbou/TeratermStation#12]
tab.yamlに
```yaml
inifile: TERATERM.INI
inirewrite:
  VTColor: 131,148,150,0,43,54
  TTProxy:
    ConnectionTimeout: '"33"'
```
と定義することで、ttl実行前にINIファイルを書き換えられるようにする。

**Comment by turbou** [comment]
接続前のINIの書き換えに対応完了。

[Wiki](https://github.com/turbou/TeratermStation/wiki/Connection-Definition)の**HTTPプロキシBASIC認証経由でSSH接続の場合**  
にサンプルを記載済み。

**Comment by turbou** [comment]
tab.yamlの書き方としては下な感じ。
```yaml
auth:
  memory: true
  autoclear: false
  group: basic

connect: connect '${ipaddress} /ssh /2 /auth=password /user=${loginuser} /passwd=${loginpassword} /f="${inifile}"

inifile: TERATERM.INI
inirewrite:
  TTProxy:
    ProxyType: '"http"'
    ProxyHost: '"oyoyo.com"'
    ProxyPort: '"80"'
    ProxyUser: '"${authuser}"'
    ProxyPass: '"${authpassword}"'
```
ProxyType, ProxyHost, ProxyPortについては、INIにべた書きの上、配布で
ProxyUser, ProxyPassだけを上記のようにプレースホルダーを使ってyamlに
記載してもよい。
